server.port=8080

spring.application.name=api-gateway

# Logging útil
logging.level.org.springframework.web=INFO
logging.level.backend.tpi.apigateway=DEBUG

# URLs para Docker
ms.solicitudes.url=http://ms-solicitudes:8081/api/v1
ms.transportes.url=http://ms-transportes:8082/api/v1